# Generated by Django 4.2.7 on 2026-03-15 14:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import scheduler_manager.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchStatus',
            fields=[
                ('batch_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('campaign_id_direct', models.IntegerField(db_index=True, help_text='Direct campaign ID for faster queries without joins', null=True)),
                ('total_messages', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sender_id', models.CharField(blank=True, help_text="Sender ID that will appear as the message sender (e.g., 'SMSINFO', 'MPESA')", max_length=11, null=True)),
                ('channels', models.JSONField(default=list, help_text='List of channels for this campaign. Options: sms, app_notification, flash_sms')),
                ('last_processed_id', models.PositiveIntegerField(default=0, help_text='Last recipient ID processed by Layer 2 (for keyset pagination)')),
                ('total_processed', models.PositiveIntegerField(default=0, help_text='Total number of messages successfully processed so far')),
                ('execution_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('PAUSED', 'Paused'), ('STOPPED', 'Stopped'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', help_text='Current execution status for Layer 2 processing', max_length=20)),
                ('execution_started_at', models.DateTimeField(blank=True, help_text='When Layer 2 started processing this campaign', null=True)),
                ('execution_completed_at', models.DateTimeField(blank=True, help_text='When Layer 2 completed processing this campaign', null=True)),
                ('execution_paused_at', models.DateTimeField(blank=True, help_text='When Layer 2 paused processing this campaign', null=True)),
                ('total_messages', models.PositiveIntegerField(default=0, help_text='Total messages in this campaign (from audience)')),
                ('sent_count', models.PositiveIntegerField(default=0, help_text='Number of messages sent to provider')),
                ('delivered_count', models.PositiveIntegerField(default=0, help_text='Number of messages confirmed delivered')),
                ('failed_count', models.PositiveIntegerField(default=0, help_text='Number of messages permanently failed')),
                ('pending_count', models.PositiveIntegerField(default=0, help_text='Number of messages still pending')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageStatus',
            fields=[
                ('message_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('campaign_id', models.IntegerField(db_index=True)),
                ('batch_id', models.CharField(db_index=True, max_length=50)),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('sender_id', models.CharField(blank=True, help_text='Sender ID used for this message', max_length=11, null=True)),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('app_notification', 'App Notification'), ('flash_sms', 'Flash SMS')], default='sms', help_text='Channel used for this message (sms, app_notification, flash_sms)', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('RETRYING', 'Retrying')], db_index=True, default='PENDING', max_length=20)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_attempt', models.DateTimeField(blank=True, null=True)),
                ('provider_message_id', models.CharField(blank=True, db_index=True, help_text="Provider's message ID for tracking (from Layer 3)", max_length=255, null=True)),
                ('provider_status', models.CharField(blank=True, help_text='Raw status from provider', max_length=50)),
                ('provider_response', models.TextField(blank=True, help_text='Provider response message', null=True)),
                ('provider_response_raw', models.JSONField(blank=True, help_text='Complete provider response for debugging', null=True)),
                ('sent_at', models.DateTimeField(blank=True, db_index=True, help_text='When message was sent to provider', null=True)),
                ('delivered_at', models.DateTimeField(blank=True, db_index=True, help_text='When delivery was confirmed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Message Statuses',
                'indexes': [models.Index(fields=['campaign_id', 'status'], name='scheduler_m_campaig_4bd305_idx'), models.Index(fields=['batch_id'], name='scheduler_m_batch_i_9a47aa_idx'), models.Index(fields=['created_at'], name='scheduler_m_created_83222f_idx'), models.Index(fields=['status', 'last_attempt'], name='scheduler_m_status_5554a7_idx'), models.Index(fields=['phone_number', 'campaign_id'], name='scheduler_m_phone_n_229abc_idx'), models.Index(fields=['sender_id'], name='scheduler_m_sender__3b14e8_idx'), models.Index(fields=['channel'], name='scheduler_m_channel_534a28_idx'), models.Index(fields=['provider_message_id'], name='scheduler_m_provide_401ec0_idx'), models.Index(fields=['sent_at'], name='scheduler_m_sent_at_fa87a1_idx'), models.Index(fields=['delivered_at'], name='scheduler_m_deliver_422b5a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipients', models.JSONField(help_text='List of recipients with msisdn and lang')),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('valid_count', models.PositiveIntegerField(default=0)),
                ('invalid_count', models.PositiveIntegerField(default=0)),
                ('database_table', models.CharField(default='scheduler_manager_audience', help_text='Table name where recipients are stored for direct DB access', max_length=100)),
                ('id_field', models.CharField(default='id', help_text='Primary key field name for keyset pagination', max_length=50)),
                ('filter_condition', models.TextField(blank=True, help_text="Additional SQL WHERE clause for filtering recipients (e.g., 'AND status = 'PENDING'')")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audience', to='scheduler_manager.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_type', models.CharField(choices=[('once', 'One Time'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='once', help_text='Type of schedule: one-time or recurring', max_length=20)),
                ('start_date', models.DateField(help_text='First date when campaign can run')),
                ('end_date', models.DateField(blank=True, help_text='Last date when campaign can run (null for infinite)', null=True)),
                ('run_days', models.JSONField(default=list, help_text='Days of week to run (0=Monday to 6=Sunday). For daily, use [0,1,2,3,4,5,6]')),
                ('time_windows', models.JSONField(default=list, help_text="List of time windows: [{'start': '08:00', 'end': '12:00'}, ...]")),
                ('timezone', models.CharField(default='UTC', help_text="Timezone for schedule (e.g., 'Africa/Addis_Ababa')", max_length=50)),
                ('campaign_status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('stopped', 'Stopped'), ('completed', 'Completed'), ('expired', 'Expired')], db_index=True, default='active', max_length=20)),
                ('current_round', models.PositiveIntegerField(default=0, help_text='Current execution round (increments after each window)')),
                ('current_window_date', models.DateField(blank=True, help_text='Current date being processed', null=True)),
                ('current_window_index', models.IntegerField(default=0, help_text='Index of current time window (0-based)')),
                ('current_window_status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('partial', 'Partial'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('next_run_date', models.DateField(blank=True, db_index=True, help_text='Next date when campaign will run', null=True)),
                ('next_run_window', models.IntegerField(blank=True, help_text='Index of next time window to run', null=True)),
                ('completed_windows', models.JSONField(default=list, help_text="History of completed windows: [{'date': '2024-01-01', 'window': 0, 'status': 'completed'}]")),
                ('total_windows_completed', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('auto_reset', models.BooleanField(default=True, help_text='Automatically reset for next window after completion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_processed_at', models.DateTimeField(blank=True, help_text='Last time this schedule was processed', null=True)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='scheduler_manager.campaign')),
            ],
            options={
                'indexes': [models.Index(fields=['campaign_status', 'is_active'], name='scheduler_m_campaig_951a8f_idx'), models.Index(fields=['schedule_type', 'next_run_date'], name='scheduler_m_schedul_a7be19_idx'), models.Index(fields=['start_date', 'end_date'], name='scheduler_m_start_d_2cb18c_idx'), models.Index(fields=['current_window_status'], name='scheduler_m_current_593b69_idx')],
            },
        ),
        migrations.CreateModel(
            name='MessageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.JSONField(default=scheduler_manager.models._default_message_content)),
                ('default_language', models.CharField(choices=[('en', 'EN'), ('am', 'AM'), ('ti', 'TI'), ('om', 'OM'), ('so', 'SO')], default='en', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='message_content', to='scheduler_manager.campaign')),
            ],
            options={
                'indexes': [models.Index(fields=['default_language'], name='scheduler_m_default_3a7841_idx')],
            },
        ),
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='checkpoint', serialize=False, to='scheduler_manager.campaign')),
                ('last_processed_index', models.PositiveIntegerField(default=0)),
                ('total_to_process', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('PAUSED', 'Paused')], default='RUNNING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='scheduler_m_status_2ba7e2_idx')],
            },
        ),
        migrations.CreateModel(
            name='CampaignProgress',
            fields=[
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='progress', serialize=False, to='scheduler_manager.campaign')),
                ('total_messages', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('delivered_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('pending_count', models.PositiveIntegerField(default=0)),
                ('progress_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('STOPPED', 'Stopped'), ('FAILED', 'Failed')], default='ACTIVE', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Campaign Progresses',
                'indexes': [models.Index(fields=['status'], name='scheduler_m_status_788eea_idx'), models.Index(fields=['progress_percent'], name='scheduler_m_progres_8d5318_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['status'], name='scheduler_m_status_abe733_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['created_by'], name='scheduler_m_created_8aee39_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['sender_id'], name='scheduler_m_sender__4882ea_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['execution_status'], name='scheduler_m_executi_33074c_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['last_processed_id'], name='scheduler_m_last_pr_d40e8c_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['-created_at'], name='scheduler_m_created_967592_idx'),
        ),
        migrations.AddField(
            model_name='batchstatus',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='scheduler_manager.campaignprogress'),
        ),
        migrations.AddIndex(
            model_name='audience',
            index=models.Index(fields=['total_count'], name='scheduler_m_total_c_0d3b01_idx'),
        ),
        migrations.AddIndex(
            model_name='audience',
            index=models.Index(fields=['database_table'], name='scheduler_m_databas_88721a_idx'),
        ),
        migrations.AddIndex(
            model_name='batchstatus',
            index=models.Index(fields=['status'], name='scheduler_m_status_6ea69b_idx'),
        ),
        migrations.AddIndex(
            model_name='batchstatus',
            index=models.Index(fields=['campaign_id_direct'], name='scheduler_m_campaig_e68544_idx'),
        ),
        migrations.AddIndex(
            model_name='batchstatus',
            index=models.Index(fields=['created_at'], name='scheduler_m_created_7e8529_idx'),
        ),
    ]
