# Generated by Django 5.2.6 on 2026-03-06 08:48

import django.core.validators
import django.db.models.deletion
import scheduler_manager.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipients', models.JSONField()),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('valid_count', models.PositiveIntegerField(default=0)),
                ('invalid_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audience', to='scheduler_manager.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='MessageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.JSONField(default=scheduler_manager.models._default_message_content)),
                ('default_language', models.CharField(choices=[('en', 'EN'), ('am', 'AM'), ('ti', 'TI'), ('om', 'OM'), ('so', 'SO')], default='en', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='message_content', to='scheduler_manager.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('frequency', models.CharField(max_length=20)),
                ('run_days', models.JSONField(default=list)),
                ('send_times', models.JSONField(default=list)),
                ('end_times', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('stop', 'Stop'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='scheduler_manager.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignProgress',
            fields=[
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='progress', serialize=False, to='scheduler_manager.campaign')),
                ('total_messages', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('pending_count', models.PositiveIntegerField(default=0)),
                ('progress_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('STOPPED', 'Stopped'), ('FAILED', 'Failed')], default='ACTIVE', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Campaign Progresses',
                'indexes': [models.Index(fields=['status'], name='scheduler_m_status_788eea_idx'), models.Index(fields=['progress_percent'], name='scheduler_m_progres_8d5318_idx')],
            },
        ),
        migrations.CreateModel(
            name='BatchStatus',
            fields=[
                ('batch_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('campaign_id_direct', models.IntegerField(db_index=True, null=True)),
                ('total_messages', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='scheduler_manager.campaignprogress')),
            ],
        ),
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='checkpoint', serialize=False, to='scheduler_manager.campaign')),
                ('last_processed_index', models.PositiveIntegerField(default=0)),
                ('total_to_process', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('PAUSED', 'Paused')], default='RUNNING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='scheduler_m_status_2ba7e2_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['status'], name='scheduler_m_status_abe733_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['created_by'], name='scheduler_m_created_8aee39_idx'),
        ),
        migrations.AddIndex(
            model_name='audience',
            index=models.Index(fields=['total_count'], name='scheduler_m_total_c_0d3b01_idx'),
        ),
        migrations.AddIndex(
            model_name='messagecontent',
            index=models.Index(fields=['default_language'], name='scheduler_m_default_3a7841_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['status', 'is_active'], name='scheduler_m_status_c22d34_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['start_date', 'end_date'], name='scheduler_m_start_d_2cb18c_idx'),
        ),
        migrations.AddIndex(
            model_name='batchstatus',
            index=models.Index(fields=['status'], name='scheduler_m_status_6ea69b_idx'),
        ),
        migrations.AddIndex(
            model_name='batchstatus',
            index=models.Index(fields=['campaign_id_direct'], name='scheduler_m_campaig_e68544_idx'),
        ),
        migrations.AddIndex(
            model_name='batchstatus',
            index=models.Index(fields=['created_at'], name='scheduler_m_created_7e8529_idx'),
        ),
    ]
