# Generated by Django 5.2.6 on 2026-02-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSScheduler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(max_length=255)),
                ('sms_content', models.TextField()),
                ('user_list', models.JSONField(default=list)),
                ('batch_count', models.IntegerField(default=100)),
                ('start_date', models.DateField()),
                ('frequency', models.CharField(choices=[('once', 'Once'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='once', max_length=20)),
                ('run_days', models.JSONField(default=list, help_text='Days of the week: 0=Mon, 1=Tue... 6=Sun')),
                ('specific_times', models.JSONField(default=list, help_text='List of times in HH:MM format')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'SMS Schedule',
                'verbose_name_plural': 'SMS Schedules',
            },
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
