# Generated by Django 5.2.6 on 2026-02-21 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_manager', '0002_smsscheduler_delete_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipients', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MessageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.JSONField()),
                ('default_language', models.CharField(default='en', max_length=10)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scheduler_manager.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('frequency', models.CharField(max_length=20)),
                ('run_days', models.JSONField(default=list)),
                ('send_times', models.JSONField(default=list)),
                ('batch_size', models.IntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scheduler_manager.campaign')),
            ],
        ),
        migrations.DeleteModel(
            name='SMSScheduler',
        ),
        migrations.AddField(
            model_name='audience',
            name='campaign',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scheduler_manager.campaign'),
        ),
    ]
