# Generated by Django 5.2.6 on 2026-02-21 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_manager', '0003_audience_campaign_messagecontent_schedule_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='batch_size',
        ),
        migrations.AddField(
            model_name='schedule',
            name='end_times',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='audience',
            name='campaign',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audience', to='scheduler_manager.campaign'),
        ),
        migrations.AlterField(
            model_name='messagecontent',
            name='campaign',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='message_content', to='scheduler_manager.campaign'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='campaign',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='scheduler_manager.campaign'),
        ),
    ]
