# Generated by Django 5.2.6 on 2026-02-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_manager', '0004_remove_schedule_batch_size_schedule_end_times_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('stop', 'Stop')], default='pending', max_length=20),
        ),
    ]
