# Generated by Django 5.2.6 on 2026-02-21 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_manager', '0005_schedule_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('stop', 'Stop'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
